version: '3'
services:
  # AI Service (No Database)
  validity-ai-server-service:
    build: ./Validity-AI/server
    container_name: validity-ai-server
    environment:
      - PASSW=0407c14bf6df0055ab809f62c89f35983f4520ce946339c916e5111fcb0e30e2
      - SALT=2623a342b266b854bc45748ae49b1723907b4b2f337c34ddcf6a1ab359fbcc21
      - ALGORITHM=HS256
      - SECRET_KEY=ebd9197c201d1e315a5bea2858c7cc50e8a21ab4be7874212cbbd7b489cede95
    ports:
      - "8000:8000"

  # Global Router Service (With Database)
  global-router-server-service:
    build: ./Global-Router/server
    container_name: global-router
    environment:
      - SECRET_KEY=ebd9197c201d1e315a5bea2858c7cc50e8a21ab4be7874212cbbd7b489cede95
      - DATABASE_URL=postgresql://postgres:postgres@global-router-db:5432/global_router_db
    ports:
      - "3000:3000"

  # Global Router Database Service (Manages User Data)
  global-router-db-service:
    image: postgres:13-alpine
    container_name: global-router-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: global_router_db
    ports:
      - "4052:5432"
    volumes:
      - global-router-db-data:/var/lib/postgresql/data

  # Washington DC Area Service (With Database)

  # Washington DC Area Database Service (Manages Regional Events)
  washington-dc-area:
    image: postgres:13-alpine
    container_name: washington-dc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: washington_dc_db
    ports:
      - "4062:5432"
    volumes:
      - washington-dc-db-data:/var/lib/postgresql/data

volumes:
  global-router-db-data:
  washington-dc-db-data: