### Test text analyzer endpoint with invalid JWT cookie
GET http://127.0.0.1:8000/api/ta
Cookie: access_token=invalidtoken

### Test text analyzer endpoint without cookie
GET http://127.0.0.1:8000/api/ta

### Test text analyzer endpoint with valid JWT cookie but no query
GET http://127.0.0.1:8000/api/ta
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTcxNzBjODdlMThhOTAzNzEyZjNlOTlmNGVmY2Q2MCIsImV4cCI6MTc1MzE0NjY4NX0.xSeV5-5QJ8ObY38l2iYFhfcKrf_D3izH0g4qLG9z524

### Test text analyzer endpoint with valid JWT cookiem and valid query
GET http://127.0.0.1:8000/api/ta?claim=There-are-donkeys-on-mars.-there-are-also-spaceships-on-the-moon.-I-like-donkeys.
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTcxNzBjODdlMThhOTAzNzEyZjNlOTlmNGVmY2Q2MCIsImV4cCI6MTc1MzE0NjY4NX0.xSeV5-5QJ8ObY38l2iYFhfcKrf_D3izH0g4qLG9z524