### Test text equivilence analyzer endpoint with invalid JWT cookie
GET http://127.0.0.1:8000/api/tea?claim-1=There-are-donkeys-on-mars&claim-2=Donkes-exist-on-mars
Cookie: access_token=invalidToken

### Test text equivilence analyzer endpoint without valid cookie
GET http://127.0.0.1:8000/api/tea?claim-1=There-are-donkeys-on-mars&claim-2=Donkes-exist-on-mars

### Test text equivilence analyzer endpoint with valid JWT cookie and valid query
GET http://127.0.0.1:8000/api/tea?claim-1=There-are-donkeys-on-mars&claim-2=Donkes-exist-on-mars
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTcxNzBjODdlMThhOTAzNzEyZjNlOTlmNGVmY2Q2MCIsImV4cCI6MTc1MzE0NjY4NX0.xSeV5-5QJ8ObY38l2iYFhfcKrf_D3izH0g4qLG9z524

### Test text equivilence analyzer endpoint without valid query
GET http://127.0.0.1:8000/api/tea
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTcxNzBjODdlMThhOTAzNzEyZjNlOTlmNGVmY2Q2MCIsImV4cCI6MTc1MzE0NjY4NX0.xSeV5-5QJ8ObY38l2iYFhfcKrf_D3izH0g4qLG9z524
