### Test API status endpoint (should require valid JWT cookie)
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "passw": "passw0rd"
}

### Test API status endpoint with invalid JWT cookie
GET http://localhost:8000/api/ta
Cookie: access_token=invalidtoken

### Test API status endpoint with valid JWT cookie
GET http://localhost:8000/api/ta
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZGE4NjJmYTNmNjgzNDM5OGUxMzQzN2FhZWEzNmI3YiIsImV4cCI6MTc1MDA1MjUxN30.8eWcvVIbQOHD6XWnpynMQRdxON8T6kd0w2JNAer9I_8