version: '3'
services:
  global-router-server-service:
    build: .
    container_name: global-router
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@global-router-db:5432/global_router_db
      - SECRET_KEY=ebd9197c201d1e315a5bea2858c7cc50e8a21ab4be7874212cbbd7b489cede95
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: .