version: '3'
services:
  global-router-server-service:
    build: .
    container_name: global-router
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@global-router-db:5432/global_router_db
      - SECRET_KEY=ebd9197c201d1e315a5bea2858c7cc50e8a21ab4be7874212cbbd7b489cede95
    ports:
      - "3000:3000"
    depends_on:
      - global-router-db-service
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: .

  # Global Router Database Service (Manages User Data)
  global-router-db-service:
    image: postgres:13-alpine
    container_name: global-router-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: global_router_db
    ports:
      - "4052:5432"
    volumes:
      - global-router-db-data:/var/lib/postgresql/data

volumes:
  global-router-db-data: